---
- name: "Apply svarog.properties template"
  template:
    src: svarog.properties.tpl
    dest: ../svarog.properties

- name: Register output for svarog.properties
  shell: cat ../svarog.properties
  register: cat_output

- name: Display output for svarog.properties
  debug:
    var: cat_output















